// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.5.0
// source: Ccc.proto

package stubs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CccClient is the client API for Ccc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CccClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type cccClient struct {
	cc grpc.ClientConnInterface
}

func NewCccClient(cc grpc.ClientConnInterface) CccClient {
	return &cccClient{cc}
}

func (c *cccClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/aaa.bbb.Ccc/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CccServer is the server API for Ccc service.
// All implementations must embed UnimplementedCccServer
// for forward compatibility
type CccServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedCccServer()
}

// UnimplementedCccServer must be embedded to have forward compatible implementations.
type UnimplementedCccServer struct {
}

func (UnimplementedCccServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedCccServer) mustEmbedUnimplementedCccServer() {}

// UnsafeCccServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CccServer will
// result in compilation errors.
type UnsafeCccServer interface {
	mustEmbedUnimplementedCccServer()
}

func RegisterCccServer(s grpc.ServiceRegistrar, srv CccServer) {
	s.RegisterService(&Ccc_ServiceDesc, srv)
}

func _Ccc_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CccServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aaa.bbb.Ccc/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CccServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ccc_ServiceDesc is the grpc.ServiceDesc for Ccc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ccc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aaa.bbb.Ccc",
	HandlerType: (*CccServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Ccc_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Ccc.proto",
}
